
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: "{{ .Stage.EnvironmentID }}-{{ .Region }}"
customTarget:
  customTargetType: cloud-run-service
deployParameters:
  customTarget/serviceID: {{ .Service.ID }}
  customTarget/image: {{ .Build.Image }}
  customTarget/projectID: {{ .Stage.ProjectID }}
  customTarget/tag: "insiders" # default tag
executionConfigs:
- usages: [RENDER, DEPLOY]
  serviceAccount: {{ .CloudDeployServiceAccount }}
