namespaces:
  - name: BATCH_CHANGES
    actions:
      - READ
      - WRITE
  - name: OWNERSHIP
    actions:
      - ASSIGN
  - name: REPO_METADATA
    actions:
      - WRITE
  - name: LICENSE_MANAGER
    actions:
      - READ
      - WRITE
excludeFromUserRole:
  - OWNERSHIP
  - LICENSE_MANAGER
